Courses/urls.py
# from django.conf.urls import url
from django.urls import path
# from django.urls.resolvers import URLPattern
from.views import register_courses,course_list


app_name = 'courses'
urlpatterns = [

    path("register/", register_courses, name = "register_courses"),
    path("list/", course_list, name = "course_list"),
    ]

Trainer/urls.py
from django.urls import path
# from django.urls.resolvers import URLPattern
from .views import register_trainer, trainer_list

app_name = 'trainer'
urlpatterns = [
    path("register/",register_trainer, name = "register_trainer"),
    path("list/",trainer_list, name = "trainer_list"),
    ]

api/urls.py
from django.urls.conf import include, path
from rest_framework import routers
from .views import StudentViewSet
from .views import TrainerViewSet
from .views import CalViewSet
from .views import CoursesViewSet

router =routers.DefaultRouter()
router.register("students/", StudentViewSet)
router.register("trainer/", TrainerViewSet)
router.register("cal/", CalViewSet)
router.register("courses/", CoursesViewSet)

app = "api"
urlpatterns= [
    path("", include(router.urls)),
]

cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url('calendar/', views.CalendarView.as_view(), name='calender'),
    url('forms/', views.event, name='event_form'), 
 

]

schoolprojects/urls.py
from django.conf import settings
from django.conf .urls .static import static
"""schoolprojects URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django import urls
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Home.urls')),
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('trainer/', include('Trainer.urls')),
    path('courses/', include('Courses.urls')),
    path('cal/', include('cal.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#All projects are kept here

student/urls.py
# from django.conf.urls import url
from django.urls import path
# from django.urls.resolvers import URLPattern
from.views import edit_student, register_student, student_list, student_profile


app_name = 'student'
urlpatterns = [
    path("register",register_student, name = "register_student"),
    path("list/", student_list, name = "student_list"),
    path("profile/<int:id>/", student_profile, name = "student_profile"),
    path("edit/<int:id>/", edit_student, name = "edit_student"),


    ]

cal/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

cal/views.py
import calendar
from datetime import date, timedelta
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.utils.safestring import mark_safe
from .forms import EventForm
from .models import *
from .utils import Calendar

# Create your views here.


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal=cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month
def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month
    
def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
  
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return redirect('cal:calender')
        
    return render(request, 'event_form.html', {'form': form})
   

cal/templates/cal_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calender</title>
</head>
<body>
  <h2>
    Welcome To codeHive 2022
  </h2>
  <div class="topnav">
    <a style="margin-top:10%;" href="{% url 'cal:event_form' %}"> EVENTS</a>
    <a style="margin-top:10%;" href="{% url 'courses:register_courses' %}"> COURSES</a>
    <a style="margin-top:10%;" href="{% url 'trainer:register_trainer' %}"> TRAINER </a>
    <a style="margin-top:10%;" href="{% url 'student:register_student' %}"> STUDENT</a>  
  
        </div>
    <h1> codeHive Calender</h1>
    {% block content %}
    <div class="heading">
    <div class="clearfix">
      <a class="btn btn-info left" href="{ % url 'cal:calendar' % }?{{ prev_month }}"> Previous Month </a>
      <a class="btn btn-info right" href="{ % url 'cal:calendar' % }?{{ next_month }}"> Next Month </a>
    </div>
    {{ calendar }}
    {% endblock %}
  </div>
    <style>
    
    div{
      text-align: right;
      margin-right: 150px;
      margin-top: 40px;
      margin-left: 30px;
      
    }
    h1{
        text-align: center;
        color: purple;
        margin-bottom: 40px;
    }
    .heading{
      border-radius: 10px;
      box-shadow: 20px;
      background-color:white;
      margin-left: 100px;
    }
    .calendar {
      width:78%;
      margin: auto;
      font-size: 13px;
    }
    
    .calendar tr, .calendar td {
      border: 1px solid plum;
    }
    
    .calendar th {
      padding: 10px;
      text-align: center;
      font-size: 28px;
      color: purple;
    }
    
    .calendar td {
      width: 70px;
      height: 50px;
      padding: 20px 0px 0px 5px;
      /* color: purple; */
    }
    h2{
    color:white;
    text-align: center;
    padding-top: 20px;
    background-color: purple;
    
    
}
    
    .month {
      font-size: 55px;
      color: purple;
    }
    
    .date {
      font-size: 16px;
      color: purple;
    }
    
    ul {
      height: 100%;
      padding: 0px 5px 0px 20px;
    }
    
    a {
      color:purple;
      font-size: 20px;
      text-decoration: none;
      padding: 10px;
      text-align: right;
    }
    body{
      background-color:whitesmoke;
    }
    </style> 
</body>
</html>

cal/templates/event_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events Form</title>
</head>
<body>
{% block title %}

{% endblock %}

{% block content %}
<h2>Welocome To codeHive 2022</h2>
<div class="topnav">
  <a style="margin-top:10%;" href="{% url 'cal:event_form' %}"> EVENTS</a>
  <a style="margin-top:10%;" href="{% url 'courses:register_courses' %}"> COURSES</a>
  <a style="margin-top:10%;" href="{% url 'trainer:register_trainer' %}"> TRAINER </a>
  <a style="margin-top:10%;" href="{% url 'student:register_student' %}"> STUDENT</a>  

      </div>
<div>
<form method="post">
    <h1>Events</h1>
  {% csrf_token %}
  <table class="form form-table">
    {{ form.as_p }}
  </table>
  <input class="btn btn-success" type="submit" value="Submit" style=" background-color: purple; border-radius: 10px; width: 100%;">

</form>
{% endblock %}
</div>

<style>
    select{
        width: 100%;
        border-radius: 10px;
        font-size: 15px;
        border: 1px solid;
        padding: 8px 10px;
        border:purple;

    }
    h2{
    color:white;
    text-align: center;
    padding-top: 20px;
    background-color: purple;
    
    
}
h1{
color:purple;
text-align: center;
/* padding-top: 20px; */

}
img{
margin-left: 130px;
width: 400px;
}
form{
text-align: center;
padding-top: 20px;

color:purple;
}

.btn btn-success{
color: purple;
}
div {
border-radius: 10px;
background-color:white;
/* padding: 20px; */
margin-left: 300px;
margin-right: 300px;


}
body{
background-color:#eee;
}

.topnav {
  overflow: hidden;
  background-color:purple;
  /* height: 70px; */
}

.topnav a {
  float:right;
  color: #f2f2f2;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
  z-index: 999;
  
  
}

.topnav a:hover {
  background-color:white;
  color:purple;
  border-radius: 10px;
}

.topnav a.active {
  background-color:purple;
  color:white;
  position: fixed;
}
</style>


</body>
</html>